# ============================================
# OPENEBS
# Storage dinamico cloud-native
# ============================================

# Abilita l'addon:
# microk8s enable openebs

# OpenEBS fornisce diverse storage class:
# - openebs-hostpath: simile a hostpath ma con più funzionalità
# - openebs-device: usa block device dedicati
# - openebs-jiva: storage replicato (cluster)

---
# PVC con OpenEBS hostpath
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openebs
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# StatefulSet con OpenEBS per database
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: openebs-hostpath
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
